import beautify from './utils/beautify.log';

beautify.log(
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?',
  '{bgred}Olá',
  'senhor! {fggreen}blz?'
);

export default beautify;
